-- 1. Create Profiles Table (Public User Data)
-- This table mirrors auth.users to allow admin to view user lists
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Trigger to auto-create profile on signup
-- Enable this to automatically populate profiles when a user signs up
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, created_at)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.created_at);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger creation (safe to run multiple times if dropped first, but IF NOT EXISTS is harder for triggers)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. Create Site Config Table (for Banner, etc.)
create table if not exists public.site_config (
  key text primary key,
  value text,
  is_active boolean default true,
  description text
);

-- Insert default Banner configs if not exist
insert into public.site_config (key, value, is_active, description)
values 
  ('event_banner_img', 'images/banner_event.jpg', true, '이벤트 배너 이미지 URL'),
  ('event_banner_show', 'true', false, '이벤트 배너 표시 여부 (true/false)')
on conflict (key) do nothing;

-- 4. Review Bookings Table (Ensure it exists)
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  room_id bigint references public.rooms not null,
  check_in date not null,
  check_out date not null,
  guests integer default 2,
  total_price integer,
  status text default 'pending', -- pending, confirmed, cancelled
  payment_status text default 'unpaid'
);

-- 5. Add 'images' column to Rooms table (for dynamic gallery)
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name = 'rooms' and column_name = 'images') then
    alter table public.rooms add column images jsonb;
  end if;
end $$;
